version: "3"

services:
  nginxauth:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mylos
  auth:
    build: .
    networks:
      - mylos
    deploy:
      mode: replicated
      replicas: 3

networks:
  mylos:
    external: true