version: "3"

services:
  nginxauth:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth1
      - auth2
      - auth3
    ports:
      - "8082:8082"
    networks:
      - mylos
  auth1:
    build: .
    container_name: auth1ng
    networks:
      - mylos
  auth2:
    build: .
    container_name: auth2ng
    networks:
      - mylos
  auth3:
    build: .
    container_name: auth3ng
    networks:
      - mylos
networks:
  mylos:
    external: true