version: "3"

services:
  nginxgeo:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mylos
  geo:
    build: .
    networks:
      - mylos
    deploy:
      mode: replicated
      replicas: 3
  redis:
    image: redis
    networks:
      - mylos
networks:
  mylos:
    external: true