version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geo1
      - geo2
      - geo3
    ports:
      - "8081:8081"

    networks:
      - mylos
  geo1:
    build: .
    container_name: geo1ng
    networks:
      - mylos
  geo2:
    build: .
    container_name: geo2ng
    networks:
      - mylos
  geo3:
    build: .
    container_name: geo3ng
    networks:
      - mylos
  redis:
    image: redis
    networks:
      - mylos
networks:
  mylos:
    external: true