version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8083:8083"
    depends_on:
      - user1
      - user2
      - user3
    networks:
      - mylos
  user:
    build: .
    container_name: userng
    networks:
      - mylos
  user1:
    build: .
    container_name: user1ng
    networks:
      - mylos
  user2:
    build: .
    container_name: user2ng
    networks:
      - mylos
  user3:
    build: .
    container_name: user3ng
    networks:
      - mylos
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userpostgres
      POSTGRES_DB: userserv
    networks:
      - mylos
networks:
  mylos:
    external: true